import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const projectRoot = process.cwd();

function extractComposeServiceBlock(compose: string, serviceName: string): string {
	const match = compose.match(new RegExp(`^  ${serviceName}:\\n([\\s\\S]*?)(?=^  [a-zA-Z0-9_-]+:|^networks:|$(?![\\s\\S]))`, "m"));
	return match?.[0] ?? "";
}

test("container runtime files exist with the expected base configuration", () => {
	const dockerfilePath = join(projectRoot, "Dockerfile");
	const composePath = join(projectRoot, "docker-compose.yml");
	const prodComposePath = join(projectRoot, "docker-compose.prod.yml");
	const dockerignorePath = join(projectRoot, ".dockerignore");
	const envExamplePath = join(projectRoot, ".env.example");
	const nginxConfigPath = join(projectRoot, "deploy", "nginx", "default.conf");
	const packageJsonPath = join(projectRoot, "package.json");
	const sidecarChromeScriptPath = join(projectRoot, "scripts", "sidecar-chrome.mjs");
	const sidecarEnsureScriptPath = join(projectRoot, "scripts", "ensure-sidecar-chrome.sh");

	assert.equal(existsSync(dockerfilePath), true);
	assert.equal(existsSync(composePath), true);
	assert.equal(existsSync(prodComposePath), true);
	assert.equal(existsSync(dockerignorePath), true);
	assert.equal(existsSync(envExamplePath), true);
	assert.equal(existsSync(nginxConfigPath), true);
	assert.equal(existsSync(sidecarChromeScriptPath), true);
	assert.equal(existsSync(sidecarEnsureScriptPath), true);

	const dockerfile = readFileSync(dockerfilePath, "utf8");
	assert.match(dockerfile, /FROM node:22-bookworm-slim/i);
	assert.match(dockerfile, /ARG APT_MIRROR_HOST=""/);
	assert.match(dockerfile, /deb\.debian\.org/);
	assert.match(dockerfile, /security\.debian\.org/);
	assert.match(dockerfile, /apt-get install -y --no-install-recommends git curl ca-certificates python3 python3-pip python3-venv python3-cryptography python3-yaml/i);
	assert.doesNotMatch(dockerfile, /pip3 install/);
	assert.match(dockerfile, /ENV HOST=0\.0\.0\.0/);
	assert.match(dockerfile, /ENV PORT=3000/);
	assert.match(dockerfile, /HEALTHCHECK/i);
	assert.match(dockerfile, /EXPOSE 3000/);
	assert.match(dockerfile, /CMD \["npm", "start"\]/);

	const compose = readFileSync(composePath, "utf8");
	const workerComposeBlock = extractComposeServiceBlock(compose, "ugk-pi-conn-worker");
	const searxngComposeBlock = extractComposeServiceBlock(compose, "ugk-pi-searxng");
	assert.match(compose, /services:/);
	assert.match(compose, /ugk-pi:/);
	assert.match(compose, /ugk-pi-conn-worker:/);
	assert.match(compose, /ugk-pi-team-worker:/);
	assert.match(compose, /ugk-pi-browser:/);
	assert.match(compose, /ugk-pi-browser-cdp:/);
	assert.match(compose, /ugk-pi-browser-chrome-01:/);
	assert.match(compose, /ugk-pi-browser-chrome-01-cdp:/);
	assert.match(compose, /ugk-pi-browser-chrome-02:/);
	assert.match(compose, /ugk-pi-browser-chrome-02-cdp:/);
	assert.match(compose, /ugk-pi-searxng:/);
	assert.match(compose, /3000:3000/);
	assert.match(compose, /127\.0\.0\.1:\$\{WEB_ACCESS_BROWSER_GUI_PORT:-3901\}:3001/);
	assert.match(compose, /HOST:\s*0\.0\.0\.0/);
	assert.match(compose, /CONN_DATABASE_PATH:\s*\/var\/lib\/ugk-pi\/conn\/conn\.sqlite/);
	assert.match(compose, /UGK_MODEL_SETTINGS_PATH:\s*\/app\/\.data\/agent\/model-settings\.json/);
	assert.match(compose, /UGK_RUNTIME_DEPS_DIR:\s*\/app\/\.runtime-deps/);
	assert.match(compose, /UGK_RUNTIME_PYTHON_VENV_DIR:\s*\/app\/\.runtime-deps\/python-venv-linux/);
	assert.match(compose, /PATH:\s*\/app\/\.runtime-deps\/python-venv-linux\/bin:/);
	assert.match(compose, /APT_MIRROR_HOST:\s*\$\{APT_MIRROR_HOST:-\}/);
	assert.match(compose, /TEAM_RUNTIME_ENABLED:\s*"true"/);
	assert.match(compose, /TEAM_DATA_DIR:\s*\/app\/\.data\/team/);
	assert.match(compose, /TEAM_USE_MOCK_RUNNER:\s*\$\{TEAM_USE_MOCK_RUNNER:-true\}/);
	assert.match(compose, /CONN_WORKER_MAX_CONCURRENCY:\s*\$\{CONN_WORKER_MAX_CONCURRENCY:-3\}/);
	assert.match(compose, /NOTIFICATION_BROADCAST_URL:\s*http:\/\/ugk-pi:3000\/v1\/internal\/notifications\/broadcast/);
	assert.match(compose, /WEB_ACCESS_BROWSER_PROVIDER:\s*direct_cdp/);
	assert.match(compose, /WEB_ACCESS_CDP_HOST:\s*172\.31\.250\.10/);
	assert.match(compose, /WEB_ACCESS_CDP_PORT:\s*9223/);
	assert.match(compose, /UGK_DEFAULT_BROWSER_ID:\s*\$\{UGK_DEFAULT_BROWSER_ID:-default\}/);
	assert.match(compose, /UGK_BROWSER_INSTANCES_JSON:\s*\$\{UGK_BROWSER_INSTANCES_JSON:-/);
	assert.match(compose, /UGK_BROWSER_SCOPE_ROUTE_CACHE_PATH:\s*\/app\/\.data\/browser-scope-routes\.json/);
	assert.match(compose, /"browserId":"chrome-01"/);
	assert.match(compose, /"browserId":"chrome-02"/);
	assert.match(compose, /WEB_ACCESS_BROWSER_PUBLIC_BASE_URL:\s*http:\/\/ugk-pi:3000/);
	assert.match(compose, /WEB_ACCESS_BROWSER_UPLOAD_APP_DIR:\s*\/app\/\.data\/browser-upload/);
	assert.match(compose, /WEB_ACCESS_BROWSER_UPLOAD_BROWSER_DIR:\s*\/config\/upload/);
	assert.match(compose, /SEARXNG_BASE_URL:\s*http:\/\/ugk-pi-searxng:8080/);
	assert.match(compose, /lscr\.io\/linuxserver\/chrome:latest/);
	assert.match(compose, /alpine\/socat:latest/);
	assert.match(compose, /network_mode:\s*"service:ugk-pi-browser"/);
	assert.match(compose, /network_mode:\s*"service:ugk-pi-browser-chrome-01"/);
	assert.match(compose, /network_mode:\s*"service:ugk-pi-browser-chrome-02"/);
	assert.match(compose, /ipv4_address:\s*172\.31\.250\.10/);
	assert.match(compose, /ipv4_address:\s*172\.31\.250\.11/);
	assert.match(compose, /ipv4_address:\s*172\.31\.250\.12/);
	assert.match(compose, /subnet:\s*172\.31\.250\.0\/24/);
	assert.match(compose, /CHROME_CLI:\s*"--remote-debugging-address=0\.0\.0\.0 --remote-debugging-port=9222/);
	assert.match(compose, /CHROME_CLI:.*--hide-crash-restore-bubble/);
	assert.match(compose, /CHROME_CLI:.*--js-flags=--max-old-space-size=1536/);
	assert.match(compose, /CHROME_CLI:.*--ozone-platform=x11/);
	assert.match(compose, /mem_limit:\s*\$\{UGK_BROWSER_MEM_LIMIT:-2g\}/);
	assert.match(compose, /mem_reservation:\s*\$\{UGK_BROWSER_MEM_RESERVATION:-512m\}/);
	assert.doesNotMatch(compose, /--ozone-platform=wayland/);
	assert.match(compose, /SELKIES_USE_BROWSER_CURSORS:\s*"true"/);
	assert.match(compose, /DISPLAY:\s*":0"/);
	assert.match(compose, /WEB_ACCESS_BROWSER_PROFILE_DIR:-\/config\/chrome-profile-sidecar/);
	assert.match(compose, /ensure-sidecar-chrome\.sh/);
	assert.match(compose, /condition:\s*service_healthy/);
	assert.match(compose, /TCP-LISTEN:9223,fork,bind=0\.0\.0\.0,reuseaddr/);
	assert.match(compose, /npm run worker:conn/);
	assert.match(compose, /npm run worker:team/);
	assert.match(compose, /node scripts\/runtime-deps\.mjs init && npm start/);
	assert.match(compose, /node scripts\/runtime-deps\.mjs init && npm run worker:conn/);
	assert.match(compose, /node scripts\/runtime-deps\.mjs init && npm run worker:team/);
	assert.doesNotMatch(compose, /sh -lc/);
	assert.match(compose, /ugk-pi-conn-db:\/var\/lib\/ugk-pi\/conn/);
	assert.match(compose, /\$\{UGK_RUNTIME_DEPS_HOST_DIR:-\.\/\.data\/runtime-deps\}:\/app\/\.runtime-deps/);
	assert.match(compose, /\$\{UGK_BROWSER_UPLOAD_DIR:-\.\/\.data\/chrome-sidecar\/upload\}:\/app\/\.data\/browser-upload/);
	assert.match(compose, /\$\{UGK_BROWSER_UPLOAD_DIR:-\.\/\.data\/chrome-sidecar\/upload\}:\/config\/upload/);
	assert.match(compose, /\$\{UGK_BROWSER_CHROME_01_CONFIG_DIR:-\.\/\.data\/chrome-sidecar-chrome-01\}:\/config/);
	assert.match(compose, /\$\{UGK_BROWSER_CHROME_02_CONFIG_DIR:-\.\/\.data\/chrome-sidecar-chrome-02\}:\/config/);
	assert.match(compose, /volumes:\s*\n\s*ugk-pi-conn-db:/);
	assert.match(workerComposeBlock, /healthcheck:\s*\n\s*disable:\s*true/);
	assert.doesNotMatch(workerComposeBlock, /ports:/);
	assert.match(searxngComposeBlock, /searxng\/searxng:latest/);
	assert.match(searxngComposeBlock, /127\.0\.0\.1:\$\{SEARXNG_HOST_PORT:-48080\}:8080/);
	assert.match(searxngComposeBlock, /SEARXNG_SECRET:\s*\$\{SEARXNG_SECRET:-replace-me-with-random-secret\}/);
	assert.match(searxngComposeBlock, /\.\/deploy\/searxng:\/etc\/searxng:ro/);
	assert.match(searxngComposeBlock, /\$\{UGK_SEARXNG_CACHE_DIR:-\.\/\.data\/searxng\}:\/var\/cache\/searxng/);
	assert.match(searxngComposeBlock, /mem_limit:\s*\$\{UGK_SEARXNG_MEM_LIMIT:-512m\}/);
	assert.match(searxngComposeBlock, /mem_reservation:\s*\$\{UGK_SEARXNG_MEM_RESERVATION:-128m\}/);
	assert.doesNotMatch(searxngComposeBlock, /0\.0\.0\.0:\$\{SEARXNG_HOST_PORT/);

	const prodCompose = readFileSync(prodComposePath, "utf8");
	const prodWorkerComposeBlock = extractComposeServiceBlock(prodCompose, "ugk-pi-conn-worker");
	const prodSearxngComposeBlock = extractComposeServiceBlock(prodCompose, "ugk-pi-searxng");
	assert.match(prodCompose, /services:/);
	assert.match(prodCompose, /ugk-pi:/);
	assert.match(prodCompose, /args:\s*\n\s*APT_MIRROR_HOST:\s*\$\{APT_MIRROR_HOST:-\}/);
	assert.match(prodCompose, /ugk-pi-conn-worker:/);
	assert.match(prodCompose, /ugk-pi-team-worker:/);
	assert.match(prodCompose, /ugk-pi-browser:/);
	assert.match(prodCompose, /ugk-pi-browser-cdp:/);
	assert.match(prodCompose, /ugk-pi-browser-chrome-01:/);
	assert.match(prodCompose, /ugk-pi-browser-chrome-01-cdp:/);
	assert.match(prodCompose, /ugk-pi-browser-chrome-02:/);
	assert.match(prodCompose, /ugk-pi-browser-chrome-02-cdp:/);
	assert.match(prodCompose, /nginx:/);
	assert.match(prodCompose, /ugk-pi-searxng:/);
	assert.match(prodCompose, /restart:\s*unless-stopped/);
	assert.match(prodCompose, /env_file:/);
	assert.match(prodCompose, /\.env/);
	assert.match(prodCompose, /UGK_MODEL_SETTINGS_PATH:\s*\/app\/\.data\/agent\/model-settings\.json/);
	assert.match(prodCompose, /UGK_RUNTIME_DEPS_DIR:\s*\/app\/\.runtime-deps/);
	assert.match(prodCompose, /UGK_RUNTIME_PYTHON_VENV_DIR:\s*\/app\/\.runtime-deps\/python-venv-linux/);
	assert.match(prodCompose, /PATH:\s*\/app\/\.runtime-deps\/python-venv-linux\/bin:/);
	assert.match(prodCompose, /APT_MIRROR_HOST:\s*\$\{APT_MIRROR_HOST:-\}/);
	assert.match(prodCompose, /TEAM_RUNTIME_ENABLED:\s*"true"/);
	assert.match(prodCompose, /TEAM_DATA_DIR:\s*\/app\/\.data\/team/);
	assert.match(prodCompose, /TEAM_USE_MOCK_RUNNER:\s*\$\{TEAM_USE_MOCK_RUNNER:-true\}/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_PROVIDER:\s*direct_cdp/);
	assert.match(prodCompose, /CONN_WORKER_MAX_CONCURRENCY:\s*\$\{CONN_WORKER_MAX_CONCURRENCY:-3\}/);
	assert.match(prodCompose, /NOTIFICATION_BROADCAST_URL:\s*http:\/\/ugk-pi:3000\/v1\/internal\/notifications\/broadcast/);
	assert.match(prodCompose, /WEB_ACCESS_CDP_HOST:\s*172\.31\.250\.10/);
	assert.match(prodCompose, /WEB_ACCESS_CDP_PORT:\s*9223/);
	assert.match(prodCompose, /UGK_DEFAULT_BROWSER_ID:\s*\$\{UGK_DEFAULT_BROWSER_ID:-default\}/);
	assert.match(prodCompose, /UGK_BROWSER_INSTANCES_JSON:\s*\$\{UGK_BROWSER_INSTANCES_JSON:-/);
	assert.match(prodCompose, /UGK_BROWSER_SCOPE_ROUTE_CACHE_PATH:\s*\/app\/\.data\/browser-scope-routes\.json/);
	assert.match(prodCompose, /"browserId":"chrome-01"/);
	assert.match(prodCompose, /"browserId":"chrome-02"/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_PUBLIC_BASE_URL:\s*http:\/\/ugk-pi:3000/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_UPLOAD_APP_DIR:\s*\/app\/\.data\/browser-upload/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_UPLOAD_BROWSER_DIR:\s*\/config\/upload/);
	assert.match(prodCompose, /SEARXNG_BASE_URL:\s*http:\/\/ugk-pi-searxng:8080/);
	assert.match(prodCompose, /127\.0\.0\.1:\$\{WEB_ACCESS_BROWSER_GUI_PORT:-3901\}:3001/);
	assert.match(prodCompose, /lscr\.io\/linuxserver\/chrome:latest/);
	assert.match(prodCompose, /alpine\/socat:latest/);
	assert.match(prodCompose, /network_mode:\s*"service:ugk-pi-browser"/);
	assert.match(prodCompose, /network_mode:\s*"service:ugk-pi-browser-chrome-01"/);
	assert.match(prodCompose, /network_mode:\s*"service:ugk-pi-browser-chrome-02"/);
	assert.match(prodCompose, /ipv4_address:\s*172\.31\.250\.10/);
	assert.match(prodCompose, /ipv4_address:\s*172\.31\.250\.11/);
	assert.match(prodCompose, /ipv4_address:\s*172\.31\.250\.12/);
	assert.match(prodCompose, /subnet:\s*172\.31\.250\.0\/24/);
	assert.match(prodCompose, /CHROME_CLI:\s*"--remote-debugging-address=0\.0\.0\.0 --remote-debugging-port=9222/);
	assert.match(prodCompose, /CHROME_CLI:.*--hide-crash-restore-bubble/);
	assert.match(prodCompose, /CHROME_CLI:.*--js-flags=--max-old-space-size=1536/);
	assert.match(prodCompose, /CHROME_CLI:.*--ozone-platform=x11/);
	assert.match(prodCompose, /mem_limit:\s*\$\{UGK_BROWSER_MEM_LIMIT:-2g\}/);
	assert.match(prodCompose, /mem_reservation:\s*\$\{UGK_BROWSER_MEM_RESERVATION:-512m\}/);
	assert.doesNotMatch(prodCompose, /--ozone-platform=wayland/);
	assert.match(prodCompose, /SELKIES_USE_BROWSER_CURSORS:\s*"true"/);
	assert.match(prodCompose, /DISPLAY:\s*":0"/);
	assert.match(prodCompose, /WEB_ACCESS_BROWSER_PROFILE_DIR:-\/config\/chrome-profile-sidecar/);
	assert.match(prodCompose, /ensure-sidecar-chrome\.sh/);
	assert.match(prodCompose, /condition:\s*service_healthy/);
	assert.match(prodCompose, /TCP-LISTEN:9223,fork,bind=0\.0\.0\.0,reuseaddr/);
	assert.match(prodCompose, /npm start/);
	assert.match(prodCompose, /npm run worker:conn/);
	assert.match(prodCompose, /npm run worker:team/);
	assert.match(prodCompose, /node scripts\/runtime-deps\.mjs init && npm start/);
	assert.match(prodCompose, /node scripts\/runtime-deps\.mjs init && npm run worker:conn/);
	assert.match(prodCompose, /node scripts\/runtime-deps\.mjs init && npm run worker:team/);
	assert.doesNotMatch(prodCompose, /sh -lc/);
	assert.match(prodCompose, /healthcheck:/);
	assert.match(prodCompose, /logs\/app/);
	assert.match(prodCompose, /logs\/nginx/);
	assert.match(prodCompose, /\$\{UGK_AGENT_DATA_DIR:-\.\/\.data\/agent\}:\/app\/\.data\/agent/);
	assert.match(prodCompose, /\$\{UGK_AGENTS_DATA_DIR:-\.\/\.data\/agents\}:\/app\/\.data\/agents/);
	assert.match(prodCompose, /\$\{UGK_BROWSER_UPLOAD_DIR:-\.\/\.data\/chrome-sidecar\/upload\}:\/app\/\.data\/browser-upload/);
	assert.match(prodCompose, /\$\{UGK_BROWSER_UPLOAD_DIR:-\.\/\.data\/chrome-sidecar\/upload\}:\/config\/upload/);
	assert.match(prodCompose, /\$\{UGK_BROWSER_CHROME_01_CONFIG_DIR:-\.\/\.data\/chrome-sidecar-chrome-01\}:\/config/);
	assert.match(prodCompose, /\$\{UGK_BROWSER_CHROME_02_CONFIG_DIR:-\.\/\.data\/chrome-sidecar-chrome-02\}:\/config/);
	assert.match(prodCompose, /\$\{UGK_RUNTIME_SKILLS_USER_DIR:-\.\/runtime\/skills-user\}:\/app\/runtime\/skills-user/);
	assert.match(prodCompose, /\$\{UGK_RUNTIME_DEPS_HOST_DIR:-\.\/\.data\/runtime-deps\}:\/app\/\.runtime-deps/);
	assert.match(prodWorkerComposeBlock, /healthcheck:\s*\n\s*disable:\s*true/);
	assert.doesNotMatch(prodWorkerComposeBlock, /ports:/);
	assert.match(prodSearxngComposeBlock, /searxng\/searxng:latest/);
	assert.match(prodSearxngComposeBlock, /127\.0\.0\.1:\$\{SEARXNG_HOST_PORT:-48080\}:8080/);
	assert.match(prodSearxngComposeBlock, /SEARXNG_SECRET:\s*\$\{SEARXNG_SECRET:-replace-me-with-random-secret\}/);
	assert.match(prodSearxngComposeBlock, /\$\{UGK_SEARXNG_CONFIG_DIR:-\.\/deploy\/searxng\}:\/etc\/searxng:ro/);
	assert.match(prodSearxngComposeBlock, /\$\{UGK_SEARXNG_CACHE_DIR:-\.\/\.data\/searxng\}:\/var\/cache\/searxng/);
	assert.match(prodSearxngComposeBlock, /mem_limit:\s*\$\{UGK_SEARXNG_MEM_LIMIT:-512m\}/);
	assert.match(prodSearxngComposeBlock, /mem_reservation:\s*\$\{UGK_SEARXNG_MEM_RESERVATION:-128m\}/);
	assert.doesNotMatch(prodSearxngComposeBlock, /0\.0\.0\.0:\$\{SEARXNG_HOST_PORT/);
	assert.match(prodCompose, /default\.conf/);
	assert.match(prodCompose, /depends_on:/);

	const envExample = readFileSync(envExamplePath, "utf8");
	assert.match(envExample, /ZHIPU_GLM_API_KEY=/);
	assert.match(envExample, /ALI_CODEPLAN_API_KEY=/);
	assert.match(envExample, /HOST=0\.0\.0\.0/);
	assert.match(envExample, /PORT=3000/);
	assert.match(envExample, /HOST_PORT=3000/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_GUI_PORT=3901/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_PROFILE_DIR=\/config\/chrome-profile-sidecar/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_PUBLIC_BASE_URL=http:\/\/ugk-pi:3000/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_UPLOAD_APP_DIR=\/app\/\.data\/browser-upload/);
	assert.match(envExample, /WEB_ACCESS_BROWSER_UPLOAD_BROWSER_DIR=\/config\/upload/);
	assert.match(envExample, /UGK_BROWSER_SCOPE_ROUTE_CACHE_PATH=\/app\/\.data\/browser-scope-routes\.json/);
	assert.match(envExample, /CONN_WORKER_MAX_CONCURRENCY=3/);
	assert.match(envExample, /SEARXNG_BASE_URL=http:\/\/ugk-pi-searxng:8080/);
	assert.match(envExample, /SEARXNG_HOST_PORT=48080/);
	assert.match(envExample, /SEARXNG_SECRET=replace-me-with-random-secret/);
	assert.match(envExample, /UGK_SEARXNG_MEM_LIMIT=512m/);
	assert.match(envExample, /UGK_SEARXNG_MEM_RESERVATION=128m/);
	assert.match(envExample, /UGK_AGENT_DATA_DIR=\.\/\.data\/agent/);
	assert.match(envExample, /UGK_AGENTS_DATA_DIR=\.\/\.data\/agents/);
	assert.match(envExample, /UGK_MODEL_SETTINGS_PATH=\/app\/\.data\/agent\/model-settings\.json/);
	assert.match(envExample, /UGK_BROWSER_UPLOAD_DIR=\.\/\.data\/chrome-sidecar\/upload/);
	assert.match(envExample, /UGK_BROWSER_CHROME_01_CONFIG_DIR=\.\/\.data\/chrome-sidecar-chrome-01/);
	assert.match(envExample, /UGK_BROWSER_CHROME_02_CONFIG_DIR=\.\/\.data\/chrome-sidecar-chrome-02/);
	assert.match(envExample, /UGK_SEARXNG_CONFIG_DIR=\.\/deploy\/searxng/);
	assert.match(envExample, /UGK_SEARXNG_CACHE_DIR=\.\/\.data\/searxng/);
	assert.match(envExample, /UGK_RUNTIME_SKILLS_USER_DIR=\.\/runtime\/skills-user/);
	assert.match(envExample, /UGK_RUNTIME_DEPS_HOST_DIR=\.\/\.data\/runtime-deps/);
	assert.match(envExample, /UGK_RUNTIME_PYTHON_VENV_DIR=/);
	assert.match(envExample, /APT_MIRROR_HOST=/);

	const searxngSettings = readFileSync(join(projectRoot, "deploy", "searxng", "settings.yml"), "utf8");
	assert.match(searxngSettings, /use_default_settings:\s*true/);
	assert.match(searxngSettings, /formats:\s*\n\s*- html\s*\n\s*- json/);
	assert.match(searxngSettings, /limiter:\s*false/);

	const dockerignore = readFileSync(dockerignorePath, "utf8");
	assert.match(dockerignore, /node_modules/);
	assert.match(dockerignore, /\.git/);
	assert.match(dockerignore, /\.data/);
	assert.match(dockerignore, /\.worktrees/);

	const nginxConfig = readFileSync(nginxConfigPath, "utf8");
	assert.match(nginxConfig, /proxy_pass http:\/\/ugk-pi:3000/);
	assert.match(nginxConfig, /location \/healthz/);
	assert.match(nginxConfig, /proxy_read_timeout\s+600s;/);
	assert.match(nginxConfig, /proxy_send_timeout\s+600s;/);
	assert.match(nginxConfig, /proxy_buffering\s+off;/);

	const packageJson = readFileSync(packageJsonPath, "utf8");
	assert.match(packageJson, /"worker:conn":\s*"tsx src\/workers\/conn-worker\.ts"/);
	assert.match(packageJson, /docker:logs:prod/);
	assert.match(packageJson, /docker:logs:nginx/);
	assert.match(packageJson, /docker:status:prod/);
	assert.match(packageJson, /docker:health:prod/);
	assert.match(packageJson, /docker:chrome:start/);
	assert.match(packageJson, /docker:chrome:restart/);
	assert.match(packageJson, /docker:chrome:check/);
	assert.match(packageJson, /docker:chrome:status/);
	assert.match(packageJson, /docker:chrome:open/);
	assert.match(packageJson, /"runtime:check":\s*"node scripts\/runtime-deps\.mjs check"/);

	const sidecarChromeScript = readFileSync(sidecarChromeScriptPath, "utf8");
	assert.match(sidecarChromeScript, /hide-crash-restore-bubble/);
	assert.match(sidecarChromeScript, /--js-flags=--max-old-space-size=1536/);
	assert.match(sidecarChromeScript, /--ozone-platform=x11/);
	assert.match(sidecarChromeScript, /export DISPLAY=:0/);
	assert.doesNotMatch(sidecarChromeScript, /command -v python3/);
	assert.doesNotMatch(sidecarChromeScript, /python is required to clear Chrome restore state/);
	assert.doesNotMatch(sidecarChromeScript, /--ozone-platform=wayland/);
	assert.doesNotMatch(sidecarChromeScript, /WAYLAND_DISPLAY=wayland-1/);
	assert.match(sidecarChromeScript, /exited_cleanly/);
	assert.match(sidecarChromeScript, /exit_type/);
	assert.match(sidecarChromeScript, /"check"/);
	assert.match(sidecarChromeScript, /"status"/);
	assert.match(sidecarChromeScript, /"open"/);
	assert.match(sidecarChromeScript, /check-deps\.mjs/);
	assert.match(sidecarChromeScript, /json\/version/);

	const sidecarEnsureScript = readFileSync(sidecarEnsureScriptPath, "utf8");
	assert.match(sidecarEnsureScript, /remote-debugging-port=9222/);
	assert.match(sidecarEnsureScript, /hide-crash-restore-bubble/);
	assert.match(sidecarEnsureScript, /--js-flags=--max-old-space-size=1536/);
	assert.match(sidecarEnsureScript, /ozone-platform=x11/);
	assert.match(sidecarEnsureScript, /SingletonLock/);
	assert.match(sidecarEnsureScript, /chrome-manual\.log/);
	assert.match(sidecarEnsureScript, /ugk-sidecar-chrome/);
	assert.match(sidecarEnsureScript, /google-chrome\.desktop/);
	assert.match(sidecarEnsureScript, /com\.google\.Chrome\.desktop/);
	assert.match(sidecarEnsureScript, /--user-data-dir="\$PROFILE_DIR"/);
});
