import test from "node:test";
import assert from "node:assert/strict";
import { buildServer } from "../src/server.js";
import { createAgentServiceStub } from "./server-test-helpers.js";

test("GET /playground returns the test UI html", async () => {
	const app = await buildServer({
		agentService: createAgentServiceStub(),
	});

	const response = await app.inject({
		method: "GET",
		url: "/playground",
	});

	assert.equal(response.statusCode, 200);
	assert.match(response.headers["content-type"] ?? "", /^text\/html/);
	assert.equal(response.headers["cache-control"], "no-store, no-cache, must-revalidate");
	assert.equal(response.headers.pragma, "no-cache");
	assert.equal(response.headers.expires, "0");
	assert.match(response.body, /UGK CLAW/);
	assert.match(response.body, /<link rel="icon" href="data:image\/svg\+xml,/);
	assert.doesNotMatch(response.body, /ugk-claw-mobile-logo\.png/);
	assert.match(response.body, /--font-sans: "OpenAI Sans"/);
	assert.match(response.body, /font-family: var\(--font-sans\)/);
	assert.match(response.body, /--font-mono: "Agave"/);
	assert.match(response.body, /\/assets\/fonts\/Agave-Regular\.ttf/);
	assert.match(response.body, /conversation-id/);
	assert.match(response.body, /file-input/);
	assert.match(response.body, /file-list/);
	assert.match(response.body, /selected-asset-list/);
	assert.match(response.body, /open-asset-library-button/);
	assert.match(response.body, /open-model-config-button/);
	assert.match(response.body, /open-model-sources-page-link/);
	assert.match(response.body, /href="\/playground\/model-sources"/);
	assert.match(response.body, /API 源管理/);
	assert.match(response.body, /model-config-dialog/);
	assert.match(response.body, /model-config-provider/);
	assert.match(response.body, /model-config-model/);
	assert.match(response.body, /验证并保存/);
	assert.match(response.body, /\/v1\/model-config/);
	assert.match(response.body, /\/v1\/model-config\/validate/);
	assert.match(response.body, /\/v1\/model-config\/default/);
	assert.match(response.body, /open-browser-workbench-button/);
	assert.match(response.body, /browser-workbench-dialog/);
	assert.match(response.body, /browser-workbench-list/);
	assert.match(response.body, /browser-workbench-targets/);
	assert.match(response.body, /function openBrowserWorkbench/);
	assert.match(response.body, /JS 内存/);
	assert.match(response.body, /页面元素/);
	assert.match(response.body, /占用偏高/);
	assert.match(response.body, /\/v1\/browsers\/" \+ encodeURIComponent\(browserId\) \+ "\/status/);
	assert.match(response.body, /\/targets\/" \+ encodeURIComponent\(targetId\) \+ "\/close/);
	assert.match(response.body, /\/start/);
	assert.match(response.body, /file-picker-action/);
	assert.match(response.body, /asset-modal-list/);
	assert.match(response.body, /close-asset-modal-button/);
	assert.match(response.body, /drop-zone/);
	assert.match(response.body, /composer-drop-target/);
	assert.match(response.body, /const chatStage = document.getElementById\("chat-stage"\)/);
	assert.match(response.body, /bindDropTarget\(chatStage\)/);
	assert.match(response.body, /bindDropTarget/);
	assert.match(response.body, /preventWindowFileDrop/);
	assert.match(response.body, /drag-overlay/);
	assert.match(response.body, /showGlobalDropHint/);
	assert.match(response.body, /document\.addEventListener\("dragenter"/);
	assert.match(response.body, /window\.addEventListener\("dragenter"/);
	assert.match(response.body, /function hasDragPayload/);
	assert.match(response.body, /function hasDroppedFiles/);
	assert.match(response.body, /function setCopyDropEffect/);
	assert.match(response.body, /function pushDragDebug/);
	assert.match(response.body, /function openAssetLibrary/);
	assert.match(response.body, /function closeAssetLibrary/);
	assert.match(response.body, /function selectAssetForReuse/);
	assert.match(response.body, /function renderSelectedAssets/);
	assert.match(response.body, /const pageRoot = document\.documentElement/);
	assert.match(response.body, /const pageBody = document\.body/);
	assert.match(response.body, /bindDropTarget\(pageRoot\)/);
	assert.match(response.body, /bindDropTarget\(pageBody\)/);
	assert.match(response.body, /dataTransfer\.items/);
	assert.match(response.body, /dataTransfer\.files/);
	assert.match(response.body, /dataTransfer\.types/);
	assert.match(response.body, /handleDroppedFiles/);
	assert.doesNotMatch(response.body, /applyFileIntentMessage/);
	assert.doesNotMatch(response.body, /__legacy_file_loaded__/);
	assert.doesNotMatch(response.body, /__legacy_pending_attachment__/);
	assert.match(response.body, /dragover/);
	assert.match(response.body, /drop/);
	assert.match(response.body, /send-button/);
	assert.match(response.body, /interrupt-button/);
	assert.match(response.body, /error-banner/);
	assert.match(response.body, /error-banner-message/);
	assert.match(response.body, /error-banner-close/);
	assert.match(response.body, /notification-live-region/);
	assert.match(response.body, /notification-toast-stack/);
	assert.match(response.body, /function connectNotificationStream\(/);
	assert.match(response.body, /new EventSource\("\/v1\/notifications\/stream"\)/);
	assert.match(response.body, /function showNotificationToast\(/);
	assert.match(response.body, /function handleNotificationBroadcastEvent\(/);
	assert.doesNotMatch(response.body, /queue-mode/);
	assert.doesNotMatch(response.body, /interrupt \/ steer/);
	assert.doesNotMatch(response.body, /wait \/ follow-up/);
	assert.doesNotMatch(response.body, /Watch The Agent Run/);
	assert.doesNotMatch(response.body, />message</);
	assert.doesNotMatch(response.body, />send</);
	assert.doesNotMatch(response.body, />interrupt</);
	assert.doesNotMatch(response.body, /id="view-skills-button"/);
	assert.match(response.body, /chat-stage/);
	assert.match(response.body, /process-note/);
	assert.match(response.body, /appendProcessEvent/);
	assert.match(response.body, /updateStreamingProcess/);
	assert.match(response.body, /transcript\.appendChild\(note\)/);
	assert.match(response.body, /getAgentApiPath\("\/debug\/skills"\)/);
	assert.match(response.body, /getAgentApiPath\("\/chat\/stream"\)/);
	assert.match(response.body, /getAgentApiPath\("\/chat\/queue"\)/);
	assert.match(response.body, /getAgentApiPath\("\/chat\/interrupt"\)/);
	assert.match(response.body, /attachments/);
	assert.match(response.body, /file-download/);
	assert.match(response.body, /selected-assets/);
	assert.match(response.body, /asset-modal-shell/);
	assert.match(response.body, /context-usage-shell/);
	assert.match(response.body, /context-usage-progress/);
	assert.match(response.body, /context-usage-summary/);
	assert.match(response.body, /context-usage-meta/);
	assert.match(response.body, /context-usage-toggle/);
	assert.match(response.body, /context-usage-battery/);
	assert.doesNotMatch(response.body, /context-usage-ring/);
	assert.match(response.body, /context-usage-dialog/);
	assert.match(response.body, /context-usage-dialog-body/);
	assert.equal(response.body.indexOf('<div class="context-usage-row">'), -1);
	assert.match(response.body, /\.context-usage-row\s*\{\s*display:\s*none;/);
	assert.match(response.body, /\.context-usage-shell\s*\{[\s\S]*grid-template-columns:\s*48px auto;/);
	assert.match(response.body, /\.context-usage-shell\s*\{[\s\S]*width:\s*88px;/);
	assert.match(response.body, /\.context-usage-shell\s*\{[\s\S]*padding:\s*5px 10px 5px 7px;/);
	assert.match(response.body, /\.context-usage-shell\s*\{[\s\S]*z-index:\s*50;/);
	assert.match(response.body, /\.context-usage-shell\s*\{[\s\S]*border-radius:\s*4px;/);
	assert.match(response.body, /\.context-usage-summary\s*\{[\s\S]*padding-right:\s*2px;/);
	assert.match(response.body, /\.context-usage-meta\s*\{[\s\S]*top:\s*calc\(100% \+ 10px\);[\s\S]*bottom:\s*auto;/);
	assert.match(response.body, /\.context-usage-meta\s*\{[\s\S]*z-index:\s*90;/);
	assert.match(response.body, /\.context-usage-meta\s*\{[\s\S]*display:\s*grid;[\s\S]*gap:\s*9px;/);
	assert.match(response.body, /\.context-usage-meta\s*\{[\s\S]*width:\s*min\(318px, calc\(100vw - 24px\)\);/);
	assert.match(response.body, /\.context-usage-meta\s*\{[\s\S]*transform:\s*translateY\(-4px\);/);
	assert.match(response.body, /\.context-usage-meta-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);/);
	assert.match(response.body, /\.context-usage-meta-model\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-wrap:\s*wrap;/);
	assert.match(response.body, /\.context-usage-progress\s*\{[\s\S]*repeating-linear-gradient/);
	assert.match(response.body, /function renderContextUsageTooltip\(/);
	assert.match(response.body, /contextUsageMeta\.innerHTML\s*=/);
	assert.match(response.body, /context-usage-meta-status/);
	assert.match(response.body, /context-usage-meta-item/);
	assert.match(response.body, /function renderContextUsageBar\(/);
	assert.match(response.body, /function syncContextUsage\(/);
	assert.match(response.body, /function estimateDraftContextTokens\(/);
	assert.match(response.body, /function buildProjectedContextUsage\(/);
	assert.match(response.body, /function openContextUsageDialog\(/);
	assert.match(response.body, /function closeContextUsageDialog\(/);
	assert.match(
		response.body,
		/function closeContextUsageDialog\(\)\s*\{[\s\S]*releasePanelFocusBeforeHide\(contextUsageDialog, contextUsageShell\);[\s\S]*contextUsageDialog\.setAttribute\("aria-hidden", "true"\);/,
	);
	assert.doesNotMatch(
		response.body,
		/function closeContextUsageDialog\(\)\s*\{[\s\S]*contextUsageDialog\.setAttribute\("aria-hidden", "true"\);[\s\S]*releasePanelFocusBeforeHide\(contextUsageDialog,/,
	);
	assert.match(response.body, /function toggleContextUsageDetails\(/);
	assert.match(response.body, /__ugkPlaygroundMarkdownParser/);
	assert.match(response.body, /globalThis\.marked/);
	assert.doesNotMatch(response.body, /CODEBLOCK/);
	assert.match(
		response.body,
		/\.message-content \.markdown-table-scroll\s*\{\s*display:\s*block;\s*width:\s*100%;\s*max-width:\s*100%;\s*overflow-x:\s*auto;/,
	);
	assert.match(response.body, /\.message-content\s*\{[\s\S]*min-width:\s*0;[\s\S]*max-width:\s*100%;/);
	assert.match(response.body, /\.message-content pre\s*\{[\s\S]*min-width:\s*0;[\s\S]*width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*overflow-x:\s*auto;/);
	assert.match(response.body, /\.message-content \.code-block\s*\{[\s\S]*display:\s*block;[\s\S]*min-width:\s*0;[\s\S]*width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*overflow:\s*hidden;/);
	assert.match(response.body, /\.message-content pre\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.message-content \.code-block\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.message-content \.code-block-toolbar\s*\{[\s\S]*border-bottom:\s*0;[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /\.message-content \.code-block pre\s*\{[\s\S]*width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*overflow-x:\s*auto;/);
	assert.match(
		response.body,
		/\.message-content table\s*\{\s*width:\s*100%;\s*max-width:\s*100%;\s*border-collapse:\s*collapse;/,
	);
	assert.match(
		response.body,
		/\.message-content th,[\s\S]*\.message-content td\s*\{[\s\S]*min-width:\s*60px;[\s\S]*max-width:\s*320px;[\s\S]*white-space:\s*normal;[\s\S]*overflow-wrap:\s*break-word;[\s\S]*word-break:\s*break-word;/,
	);
	assert.match(response.body, /wrapper\.className = "markdown-table-scroll";/);
	assert.match(response.body, /:root\[data-theme="light"\] \.message-content \.markdown-table-scroll,[\s\S]*background:\s*var\(--chat-table-bg\);/);
	assert.match(response.body, /:root\[data-theme="light"\] \.message-content th,[\s\S]*border-right-color:\s*#c8d6ea;[\s\S]*background:\s*#dce8f8;/);
	assert.match(response.body, /:root\[data-theme="light"\] \.message-content td,[\s\S]*border-right-color:\s*#d7e1ee;[\s\S]*color:\s*#26344f;/);
	assert.match(response.body, /:root\[data-theme="light"\] \.message-content \.code-block-toolbar,[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /:root\[data-theme="light"\] \.task-inbox-result-bubble \.message-content \.code-block-toolbar,[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /:root\[data-theme="light"\] \.assistant-run-log-trigger\.ok \.assistant-run-log-hint,[\s\S]*color:\s*#08784b;/);
	assert.match(response.body, /:root\[data-theme="light"\] \.assistant-status-shell\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /:root\[data-theme="light"\] \.assistant-status-summary\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /matchMedia\("\(max-width: 640px\)"\)/);
	assert.match(response.body, /getAgentApiPath\("\/chat\/status"\)/);
	assert.match(response.body, /mode:\s*"steer"/);
	assert.match(response.body, /height: calc\(100vh - 40px\)/);
	assert.match(response.body, /\.chat-stage\s*\{[\s\S]*display: flex;/);
	assert.match(response.body, /\.chat-stage\s*\{[\s\S]*flex-direction: column;/);
	assert.match(response.body, /\.transcript\s*\{[\s\S]*flex: 1 1 auto;/);
	assert.match(response.body, /\.transcript\s*\{[\s\S]*display: grid;/);
	assert.match(response.body, /\.transcript-pane\s*\{[\s\S]*align-items: stretch;/);
	assert.match(response.body, /--conversation-width: 640px;/);
	assert.match(response.body, /\.transcript-pane\s*\{[\s\S]*width: min\(var\(--conversation-width\), 100%\);/);
	assert.match(response.body, /\.transcript\s*\{[\s\S]*justify-items: stretch;/);
	assert.match(response.body, /\.transcript\s*\{[\s\S]*width: 100%;/);
	assert.match(response.body, /\.message\s*\{[\s\S]*justify-items: stretch;/);
	assert.match(response.body, /\.message\s*\{[\s\S]*width: 100%;/);
	assert.match(response.body, /\.message\s*\{[\s\S]*padding: 16px 0 0;/);
	assert.match(response.body, /\.message-meta,\s*\.message-body\s*\{[\s\S]*width: 100%;/);
	assert.match(response.body, /\.message-body\s*\{[\s\S]*border-radius: 4px;/);
	assert.match(response.body, /\.message-body\s*\{[\s\S]*background: var\(--chat-assistant-bg\);/);
	assert.match(response.body, /\.message-body\s*\{[\s\S]*border: 0;/);
	assert.match(response.body, /\.message-body\s*\{[\s\S]*box-shadow: none;/);
	assert.match(response.body, /\.message-body\s*\{[\s\S]*backdrop-filter: none;/);
	assert.match(response.body, /\.message\.user \.message-body\s*\{[\s\S]*background:\s*var\(--chat-user-bg\);/);
	assert.match(response.body, /\.message\.user \.message-meta\s*\{[\s\S]*flex-direction:\s*row-reverse;/);
	assert.match(response.body, /meta\.innerHTML = "<strong>YOU<\/strong><span>" \+ metaTime \+ "<\/span>";/);
	assert.doesNotMatch(response.body, /:root\[data-theme="light"\] \.message\.user \.message-body::after/);
	assert.match(response.body, /:root\[data-theme="light"\] \.message\.user \.message-content\s*\{[\s\S]*color:\s*var\(--chat-user-fg\);/);
	assert.match(response.body, /\.chat-stage\s*\{[\s\S]*position:\s*relative;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*position:\s*absolute;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*display:\s*none;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) auto;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*top:\s*0;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*left:\s*50%;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*transform:\s*translateX\(-50%\);/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*border-radius:\s*4px;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*background:\s*#2f1119;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*z-index:\s*6;/);
	assert.match(response.body, /\.chat-stage > \.error-banner\s*\{[\s\S]*z-index:\s*95;/);
	assert.match(response.body, /\.chat-stage > \.notification-live-region\s*\{[\s\S]*z-index:\s*90;/);
	assert.match(response.body, /\.error-banner\s*\{[\s\S]*pointer-events:\s*auto;/);
	assert.match(response.body, /\.error-banner\.visible\s*\{[\s\S]*display:\s*grid;/);
	assert.match(response.body, /\.error-banner\[hidden\]\s*\{[\s\S]*display:\s*none !important;/);
	assert.match(response.body, /\.error-banner-close\s*\{[\s\S]*border-radius:\s*4px;/);
	assert.match(response.body, /\.error-banner-close\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.error-banner-close\s*\{[\s\S]*background:\s*#421823;/);
	assert.match(response.body, /<div id="error-banner" class="error-banner" role="alert" hidden>/);
	assert.match(response.body, /errorBanner\.hidden = false;/);
	assert.match(response.body, /errorBanner\.hidden = true;/);
	assert.match(response.body, /errorBannerClose\.addEventListener\("click", \(\) => \{\s*clearError\(\);\s*\}\);/);
	assert.doesNotMatch(response.body, /\.shell\[data-stage-mode="landing"\] \.error-banner\s*\{/);
	assert.match(response.body, /\.message\.user \.message-content\s*\{[\s\S]*text-align:\s*left;/);
	assert.doesNotMatch(response.body, /\.message\.user \.message-content\s*\{[^}]*text-align:\s*right;/);
	assert.match(response.body, /function formatControlActionReason\(action, reason\)\s*\{/);
	assert.match(response.body, /function getControlActionErrorMessage\(action, payload, fallbackMessage\)\s*\{/);



	assert.match(response.body, /updateStreamingProcess\("ok",/);
	assert.match(response.body, /state\.conversationId\)/);
	assert.doesNotMatch(response.body, /__legacy_queue_error_copy__/);
	assert.doesNotMatch(response.body, /__legacy_interrupt_error_copy__/);
	assert.match(response.body, /const visualKind = kind === "user" \? "user" : "assistant";/);
	assert.match(response.body, /card\.className = "message " \+ visualKind;/);
	assert.match(response.body, /card\.dataset\.messageKind = kind;/);
	assert.match(response.body, /function canOpenConnRunDetails\(entry\)/);
	assert.match(response.body, /function openConnRunDetails\(entry, restoreFocusElement\)/);
	assert.match(response.body, /open-conn-manager-button/);
	assert.match(response.body, /conn-manager-dialog/);
	assert.match(response.body, /conn-manager-list/);
	assert.match(response.body, /id="runtime-summary"/);
	assert.match(response.body, /id="runtime-model-value"/);
	assert.match(response.body, /id="runtime-browser-value"/);
	assert.match(response.body, /function renderRuntimeSummary\(\)/);
	assert.match(response.body, /function syncRuntimeSummary\(\)/);
	assert.match(response.body, /当前 API 源/);
	assert.match(response.body, /当前 Chrome/);
	assert.doesNotMatch(response.body, /查看 conn、暂停或恢复调度、立即入队一次运行/);
	assert.match(response.body, /function openConnManager\(/);
	assert.match(response.body, /function loadConnManager\(/);
	assert.match(response.body, /function hydrateConnManagerRunsFromList\(/);
	assert.match(response.body, /function renderConnManager\(/);
	assert.match(response.body, /function runConnNow\(/);
	assert.match(response.body, /function hasConnManagerRunInFlight\(connId\)/);
	assert.match(response.body, /const CONN_RUN_REFRESH_MAX_ATTEMPTS = 120/);
	assert.match(response.body, /state\.connManagerActionConnId === conn\.connId && state\.connManagerActionKind === "run" \? "入队中" : hasRunInFlight \? "执行中" : "立即执行"/);
	assert.match(response.body, /conn\.status === "paused" \? "恢复中" : "暂停中"/);
	assert.match(response.body, /deleteSelectedConnsButton\.textContent = state\.connManagerActionKind === "bulk-delete" \? "删除中" : "删除所选"/);
	assert.match(response.body, /setConnManagerNotice\("已触发执行，正在后台运行："/);
	assert.match(response.body, /scheduleConnManagerRunRefresh\(conn\.connId, 0\)/);
	assert.match(response.body, /function toggleConnPaused\(/);
	assert.match(response.body, /function deleteConn\(conn\)/);
	assert.doesNotMatch(response.body, /conns\.map\(async \(conn\)/);
	assert.match(response.body, /conn-manager-filter/);
	assert.match(response.body, /conn-manager-selected-count/);
	assert.match(response.body, /delete-selected-conns-button/);
	assert.match(response.body, /function getVisibleConnManagerItems\(/);
	assert.match(response.body, /connManagerUnreadLatestRunTimesByConnId: \{\}/);
	assert.match(response.body, /function getConnUnreadTimeMs\(conn\)/);
	assert.match(response.body, /state\.connManagerUnreadLatestRunTimesByConnId\?\.\[conn\?\.connId\]/);
	assert.match(response.body, /function getConnLifecycleSortRank\(conn\)[\s\S]*conn\?\.status === "active"[\s\S]*conn\?\.status === "paused"[\s\S]*conn\?\.status === "completed"/);
	assert.match(response.body, /function getConnNextRunTimeMs\(conn\)/);
	assert.match(response.body, /function getConnLatestRunTimeMs\(/);
	assert.match(response.body, /function compareConnManagerItems\(/);
	assert.match(response.body, /\.sort\(compareConnManagerItems\)/);
	assert.match(response.body, /\.conn-manager-status\.completed/);
	assert.match(response.body, /function deleteSelectedConns\(/);
	assert.match(response.body, /\/v1\/conns\/bulk-delete/);
	assert.match(response.body, /delete-selected-conns-button/);
	assert.match(response.body, /method:\s*"DELETE"/);
	assert.match(response.body, /\/v1\/conns\/"\s*\+\s*encodeURIComponent\(conn\.connId\)/);
	assert.match(response.body, /open-conn-editor-button/);
	assert.match(response.body, /conn-editor-dialog/);
	assert.match(response.body, /conn-editor-title/);
	assert.match(response.body, /conn-editor-form/);
	assert.match(response.body, /conn-editor-target-type/);
	assert.match(response.body, /conn-editor-schedule-kind/);
	assert.match(response.body, /conn-editor-target-row/);
	assert.match(response.body, /\.conn-editor-field\[hidden\]/);
	assert.match(response.body, /\.conn-editor-field\.is-hidden/);
	assert.match(response.body, /conn-editor-schedule-panel/);
	assert.match(response.body, /conn-editor-title-input/);
	assert.match(response.body, /conn-editor-execution-type/);
	assert.match(response.body, /conn-editor-team-group-id/);
	assert.match(response.body, /function fetchTeamTaskGroups\(/);
	assert.match(response.body, /\/v1\/team\/task-groups/);
	assert.match(response.body, /function getTeamTaskGroupValidationMessage\(group\)/);
	assert.match(response.body, /option\.textContent \+= "（不可运行）";/);
	assert.match(response.body, /option\.disabled = true;/);
	assert.match(response.body, /function buildConnExecutionPayload\(/);
	assert.match(response.body, /throw new Error\("请先选择可运行的 Team Group"\)/);
	assert.match(response.body, /const execution = buildConnExecutionPayload\(\);/);
	assert.match(response.body, /execution,/);
	assert.match(response.body, /type: "team_group"/);
	assert.match(response.body, /execution\.type === "team_group"/);
	assert.match(response.body, /function appendConnRunDetailLinkRow\(section, label, href\)/);
	assert.match(
		response.body,
		/appendConnRunDetailLinkRow\(group, "Group JSON", groupId \? "\/v1\/team\/task-groups\/" \+ encodeURIComponent\(groupId\) : ""\)/,
	);
	assert.match(
		response.body,
		/appendConnRunDetailLinkRow\(group, "GroupRun JSON", groupRunId \? "\/v1\/team\/task-group-runs\/" \+ encodeURIComponent\(groupRunId\) : ""\)/,
	);
	assert.match(response.body, /const groupRunStartStatus = String\(snapshot\.groupRunStartStatus \|\| ""\);/);
	assert.match(response.body, /const groupRunStartError = String\(snapshot\.groupRunStartError \|\| ""\);/);
	assert.match(response.body, /appendConnRunDetailRow\(group, "groupRunStartStatus", groupRunStartStatus, \{ asCode: true \}\);/);
	assert.match(response.body, /appendConnRunDetailRow\(group, "groupRunStartError", groupRunStartError, \{ asCode: true \}\);/);
	assert.match(response.body, /link\.target = "_blank";/);
	assert.match(response.body, /link\.rel = "noreferrer";/);
	assert.match(
		response.body,
		/const isSkippedTeamGroupRun = snapshot\.skipped === true;[\s\S]*if \(isSkippedTeamGroupRun\) \{[\s\S]*appendConnRunDetailRow\(group, "Skipped"/,
	);
	assert.doesNotMatch(response.body, /run\.status === "failed" && run\.errorText[\s\S]{0,260}Skipped/);
	assert.match(response.body, /conn-editor-prompt/);
	assert.match(response.body, /conn-editor-once-at/);
	assert.match(response.body, /conn-editor-interval-start/);
	assert.match(response.body, /conn-editor-interval-minutes/);
	assert.match(response.body, /\/vendor\/flatpickr\/flatpickr\.min\.css/);
	assert.match(response.body, /\/vendor\/flatpickr\/flatpickr\.min\.js/);
	assert.match(response.body, /\/vendor\/flatpickr\/l10n\/zh\.js/);
	assert.match(response.body, /id="conn-editor-once-at"[\s\S]*type="text"[\s\S]*data-conn-time-picker="datetime"/);
	assert.match(response.body, /id="conn-editor-interval-start"[\s\S]*type="text"[\s\S]*data-conn-time-picker="datetime"/);
	assert.match(response.body, /id="conn-editor-time-of-day"[\s\S]*type="text"[\s\S]*data-conn-time-picker="time"/);
	assert.match(response.body, /data-schedule-panel="once"/);
	assert.match(response.body, /data-schedule-panel="interval"/);
	assert.match(response.body, /data-schedule-panel="daily"/);
	assert.match(response.body, /conn-editor-advanced/);
	assert.match(response.body, /conn-editor-time-of-day/);
	assert.match(response.body, /function initializeConnEditorTimePickers\(/);
	assert.match(response.body, /initializeConnEditorTimePickers\(\);/);
	assert.match(response.body, /disableMobile:\s*true/);
	assert.match(response.body, /enableTime:\s*true/);
	assert.match(response.body, /time_24hr:\s*true/);
	assert.match(response.body, /noCalendar:\s*timeOnly/);
	assert.match(response.body, /dateFormat:\s*timeOnly \? "H:i" : "Y-m-d\\\\TH:i"/);
	assert.match(response.body, /minuteIncrement:\s*5/);
	assert.match(response.body, /\.conn-time-picker-calendar\s*\{/);
	assert.match(response.body, /function parseConnCronExpression\(/);
	assert.match(response.body, /function parseConnTimeOfDay\(/);
	assert.match(response.body, /match\(\/\^\(\\d\{1,2\}\):\(\\d\{2\}\)/);
	assert.doesNotMatch(response.body, /match\(\/\^\(\\\\d\{1,2\}\):\(\\\\d\{2\}\)/);
	assert.match(response.body, /function inferConnScheduleMode\(/);
	assert.match(response.body, /function buildConnDailyCronExpression\(/);
	assert.match(response.body, /conn-editor-profile-id/);
	assert.match(response.body, /conn-editor-browser-id/);
	assert.match(response.body, /conn-editor-model-provider/);
	assert.match(response.body, /conn-editor-model-id/);
	assert.match(response.body, /conn-editor-agent-spec-id/);
	assert.match(response.body, /conn-editor-skill-set-id/);
	assert.doesNotMatch(response.body, /conn-editor-model-policy-id/);
	assert.match(response.body, /conn-editor-upgrade-policy/);
	assert.match(response.body, /conn-editor-max-run-seconds/);
	assert.match(response.body, /conn-editor-asset-refs/);
	assert.match(response.body, /conn-editor-pick-assets-button/);
	assert.match(response.body, /conn-editor-upload-assets-button/);
	assert.match(response.body, /conn-editor-asset-file-input/);
	assert.match(response.body, /conn-editor-selected-assets/);
	assert.match(response.body, /connEditorUploadingAssets/);
	assert.match(response.body, /FormData/);
	assert.match(response.body, /\/v1\/assets\/upload/);
	assert.doesNotMatch(response.body, /collectAttachments/);
	assert.doesNotMatch(response.body, /arrayBufferToBase64/);
	assert.doesNotMatch(response.body, /pendingAttachments/);
	assert.doesNotMatch(response.body, /renderAttachmentList/);
	assert.doesNotMatch(response.body, /estimateAttachmentTokenCount/);
	assert.match(response.body, /PROMPT_TEXT_ASSET_FALLBACK_CHARS = 24000/);
	assert.match(response.body, /function estimateStoredTextAssetTokenCount\(sizeBytes\)/);
	assert.match(response.body, /function estimateMetadataAssetTokenCount\(asset\)/);
	assert.match(response.body, /上传中/);
	assert.match(response.body, /上传失败/);
	assert.match(response.body, /conn-editor-target-id-label/);
	assert.match(response.body, /conn-editor-target-id-hint/);
	assert.match(response.body, /function describeConnTargetInput\(/);
	assert.match(response.body, /function buildConnTargetPayload\(\)/);
	assert.match(response.body, /conn-editor-target-preview/);
	assert.match(response.body, /option value="task_inbox"/);
	assert.match(response.body, /label\.textContent = "任务消息";/);
	assert.match(response.body, /detail\.textContent = "后台任务结果会投递到任务消息页";/);
	assert.match(response.body, /id\.textContent = targetId \|\| "填写 chat id";/);
	assert.match(response.body, /id\.textContent = targetId \|\| "填写 open id";/);
	assert.doesNotMatch(response.body, /label\.textContent = "\?{3,}";/);
	assert.doesNotMatch(response.body, /detail\.textContent = "\?{3,}";/);
	assert.doesNotMatch(response.body, /option value="current_conversation"/);
	assert.doesNotMatch(response.body, /option value="conversation"/);
	assert.doesNotMatch(response.body, /function describeConversationTarget\(/);
	assert.match(response.body, /function renderConnEditorTargetPreview\(/);
	assert.match(response.body, /function setConnManagerNotice\(/);
	assert.match(response.body, /conn-manager-notice/);
	assert.match(response.body, /state\.connManagerHighlightedConnId/);
	assert.match(response.body, /conn-manager-run-summary/);
	assert.match(response.body, /details\.className = "conn-manager-run-details";/);
	assert.match(response.body, /function describeConnStatusLabel\(/);
	assert.match(response.body, /function describeConnScheduleSummary\(/);
	assert.match(response.body, /function describeActivitySourceLabel\(/);
	assert.match(response.body, /结果发到：/);
	assert.match(response.body, /执行方式：/);
	assert.match(response.body, /运行节奏：/);
	assert.match(response.body, /function openConnEditor\(/);
	assert.match(response.body, /function submitConnEditor\(/);
	assert.match(response.body, /x-ugk-browser-binding-confirmed/);
	assert.match(response.body, /method:\s*isEditing \? "PATCH" : "POST"/);
	assert.match(response.body, /isEditing \? "\/v1\/conns\/" \+ encodeURIComponent\(state\.connEditorConnId\) : "\/v1\/conns"/);
	assert.match(response.body, /function scheduleConversationLayoutSync\(/);
	assert.match(response.body, /function scheduleResumeConversationSync\(/);
	assert.match(response.body, /function scheduleConversationHistoryPersist\(/);
	assert.match(response.body, /\.message\.assistant \.message-content\s*\{[\s\S]*font-size:\s*13px;[\s\S]*line-height:\s*1\.78;/);
	assert.match(response.body, /\.message\.assistant \.message-content h1\s*\{[\s\S]*font-size:\s*18px;/);
	assert.match(response.body, /\.message\.assistant \.message-content h2\s*\{[\s\S]*font-size:\s*16px;/);
	assert.match(response.body, /\.message\.assistant \.message-content h3\s*\{[\s\S]*font-size:\s*14px;/);
	assert.match(response.body, /\.message\.assistant \.message-content a\s*\{[\s\S]*color:\s*#8fd6ff;/);
	assert.match(response.body, /\.message\.user \.message-content a\s*\{[\s\S]*color:\s*#bfffd4;/);
	assert.match(response.body, /\.message\.user \.file-chip\s*\{[\s\S]*background:\s*#21543a;/);
	assert.match(response.body, /\.message\.user \.file-chip-badge\s*\{[\s\S]*color:\s*#b9f7d2;/);
	assert.match(response.body, /\.message\.user \.file-chip-label\s*\{[\s\S]*color:\s*#e9fff2;/);
	assert.match(response.body, /\.message\.assistant \.message-content code\s*\{[\s\S]*color:\s*#ffe6ad;/);
	assert.match(response.body, /\.message\.assistant \.message-content blockquote\s*\{[\s\S]*background:\s*#123329;/);
	assert.match(response.body, /\.message\.assistant \.message-content th\s*\{[\s\S]*background:\s*rgba\(143, 214, 255, 0\.1\);/);
	assert.doesNotMatch(response.body, /\.message\.user \.message-content h1\s*\{[\s\S]*font-size:\s*18px;/);
	assert.match(response.body, /open-task-inbox-button/);
	assert.match(response.body, /mobile-menu-task-inbox-button/);
	assert.match(response.body, /task-inbox-view/);
	assert.match(response.body, /task-inbox-list/);
	assert.doesNotMatch(response.body, /id="desktop-file-menu"/);
	assert.doesNotMatch(response.body, /function setDesktopFileMenuOpen\(open\)/);
	assert.match(response.body, /id="file-picker-action" class="composer-file-action"/);
	assert.match(response.body, /filePickerAction\.addEventListener\("click", \(\) => \{[\s\S]*fileInput\.click\(\);/);
	assert.match(response.body, /openAssetLibraryButton\.addEventListener\("click", \(\) => \{[\s\S]*toggleWorkspacePanel/);
	assert.doesNotMatch(response.body, /\.desktop-file-menu:hover \.desktop-file-menu-panel/);
	assert.doesNotMatch(response.body, /\.desktop-file-menu:focus-within \.desktop-file-menu-panel/);
	assert.doesNotMatch(response.body, /\.desktop-file-menu\[data-open="true"\] \.desktop-file-menu-panel/);
	assert.match(response.body, /<main id="chat-stage" class="chat-stage" data-workspace-mode="chat">/);
	assert.match(response.body, /function setWorkspaceMode\(mode, options\)/);
	assert.match(response.body, /function openWorkspacePanel\(mode, panel, options\)/);
	assert.match(response.body, /function closeWorkspacePanel\(mode, panel\)/);
	assert.match(response.body, /function closeInactiveWorkspacePanels\(activeMode\)/);
	assert.match(response.body, /function isDesktopWorkspaceMode\(\)/);
	assert.match(response.body, /workspace-contained/);
	assert.match(response.body, /chatStage\.dataset\.workspaceMode = state\.workspaceMode/);
	assert.match(response.body, /if \(activeMode !== "assets" && state\.assetModalOpen\)/);
	assert.match(response.body, /if \(activeMode !== "conn" && state\.connManagerOpen\)/);
	assert.match(response.body, /if \(activeMode !== "task" && state\.taskInboxOpen\)/);
	assert.match(response.body, /openAssetLibrary\(openAssetLibraryButton, \{ mode: "workspace" \}\)/);
	assert.match(response.body, /openTaskInbox\(openTaskInboxButton, \{ mode: "workspace" \}\)/);
	assert.match(response.body, /window\.location\.assign\("\/playground\/conn"\)/);
	assert.match(response.body, /window\.location\.assign\("\/playground\/agents"\)/);
	assert.match(response.body, /function shouldOpenChatViewFromUrl\(\)/);
	assert.match(response.body, /params\.get\("view"\) === "chat"/);
	assert.match(response.body, /function clearChatViewUrlHint\(\)/);
	assert.match(response.body, /if \(shouldOpenChatViewFromUrl\(\)\) \{[\s\S]*shell\.dataset\.home = "false";[\s\S]*ensureCurrentConversation\(\{ silent: true \}\);/);
	assert.doesNotMatch(response.body, /window\.open\("\/playground\/conn", "_blank"\)/);
	assert.doesNotMatch(response.body, /window\.open\("\/playground\/agents", "_blank"\)/);
	assert.match(response.body, /<a class="telemetry-card telemetry-action" href="\/playground\/team" data-tooltip-title="Team Runtime"/);
	assert.match(response.body, /<a href="\/playground\/team" class="mobile-overflow-menu-item" role="menuitem">/);
	assert.doesNotMatch(response.body, /href="\/playground\/team"[^>]*target="_blank"/);
	assert.doesNotMatch(response.body, /function loadAssetLibrary\(/);
	assert.doesNotMatch(response.body, /state\.assetItems/);
	assert.doesNotMatch(response.body, /data-primary-view="chat"/);
	assert.match(response.body, /task-inbox-unread-badge/);
	assert.match(response.body, /mobile-overflow-task-inbox-badge/);
	assert.match(response.body, /mobile-topbar-notification-badge/);
	assert.match(response.body, /mark-all-task-inbox-read-button/);
	assert.match(response.body, /markAllTaskInboxReadButton\.textContent = state\.taskInboxMarkingRead \? "处理中" : "全部已读"/);
	assert.match(response.body, /refreshTaskInboxButton\.textContent = "刷新中"/);
	assert.doesNotMatch(response.body, /task-inbox-filter-unread-button/);
	assert.doesNotMatch(response.body, /task-inbox-filter-all-button/);
	assert.match(response.body, /task-inbox-load-more-button/);
	assert.match(response.body, /task-inbox-item-unread-dot/);
	assert.match(response.body, /task-inbox-item-time/);
	assert.doesNotMatch(response.body, /选中后会立刻回到当前输入区/);
	assert.match(response.body, /class="topbar asset-modal-head"[\s\S]*id="close-asset-modal-button"[\s\S]*aria-label="返回对话"[\s\S]*id="asset-modal-title"[\s\S]*id="asset-modal-count"[\s\S]*id="refresh-assets-button"/);
	assert.match(response.body, /class="topbar asset-modal-head mobile-work-topbar"[\s\S]*id="close-conn-manager-button"[\s\S]*aria-label="返回对话"[\s\S]*id="conn-manager-title"[\s\S]*id="open-conn-editor-button"[\s\S]*id="refresh-conn-manager-button"/);
	assert.match(response.body, /class="topbar asset-modal-head mobile-work-topbar"[\s\S]*id="close-conn-editor-button"[\s\S]*aria-label="返回对话"[\s\S]*id="conn-editor-title"[\s\S]*id="save-conn-editor-button"[\s\S]*id="cancel-conn-editor-button"/);
	assert.match(response.body, /class="topbar pane-head task-inbox-head"[\s\S]*id="close-task-inbox-button"[\s\S]*aria-label="返回对话"[\s\S]*id="task-inbox-title">任务消息[\s\S]*id="task-inbox-unread-count"[\s\S]*id="mark-all-task-inbox-read-button"[\s\S]*id="refresh-task-inbox-button"/);
	assert.doesNotMatch(response.body, /asset-head-breadcrumb/);
	assert.doesNotMatch(response.body, /task-inbox-head-breadcrumb/);
	assert.doesNotMatch(response.body, /工作区 \//);
	assert.doesNotMatch(response.body, /id="close-asset-modal-button"[^>]*>回到对话/);
	assert.doesNotMatch(response.body, /id="close-conn-manager-button"[^>]*>回到对话/);
	assert.doesNotMatch(response.body, /id="close-conn-editor-button"[^>]*>回到对话/);
	assert.doesNotMatch(response.body, /id="close-task-inbox-button"[^>]*>回到对话/);
	assert.doesNotMatch(response.body, /asset-modal-page-actions[\s\S]*refresh-assets-button/);
	assert.doesNotMatch(response.body, /conn-manager-primary-actions[\s\S]*open-conn-editor-button/);
	assert.doesNotMatch(response.body, /conn-editor-page-actions[\s\S]*save-conn-editor-button/);
	assert.doesNotMatch(response.body, /task-inbox-controls[\s\S]*task-inbox-filter-unread-button/);
	assert.match(response.body, /\.task-inbox-view\s*\{[\s\S]*position:\s*fixed;[\s\S]*inset:\s*0;[\s\S]*z-index:\s*60;/);
	assert.match(response.body, /\.task-inbox-view\.open\s*\{[\s\S]*display:\s*flex;/);
	assert.match(response.body, /\.chat-stage > \.workspace-contained\s*\{[\s\S]*position:\s*absolute;[\s\S]*inset:\s*0;/);
	assert.match(response.body, /\.chat-stage\[data-workspace-mode="assets"\] > #asset-modal\.workspace-contained/);
	assert.match(response.body, /\.chat-stage\[data-workspace-mode="conn"\] > #conn-manager-dialog\.workspace-contained/);
	assert.match(response.body, /\.chat-stage\[data-workspace-mode="task"\] > #task-inbox-view\.workspace-contained/);
	assert.match(response.body, /@media \(max-width: 640px\) \{[\s\S]*\.workspace-contained\s*\{[\s\S]*position:\s*fixed;/);
	assert.match(response.body, /\.task-inbox-pane\s*\{[\s\S]*height:\s*min\(78vh, 760px\);[\s\S]*border-radius:\s*8px;/);
	assert.match(response.body, /\.asset-modal-head\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /\.asset-modal-head\s*\{[\s\S]*flex-direction:\s*row;/);
	assert.match(response.body, /\.asset-modal-actions\s*\{[\s\S]*flex-wrap:\s*nowrap;[\s\S]*overflow-x:\s*auto;/);
	assert.match(response.body, /\.conn-manager-toolbar\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /\.context-usage-dialog-panel\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.context-usage-dialog-panel\s*\{[\s\S]*border-radius:\s*8px;/);
	assert.match(response.body, /\.context-usage-dialog-panel\s*\{[\s\S]*background:[\s\S]*#060711;/);
	assert.match(response.body, /\.context-usage-dialog-head\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /\.context-usage-dialog-close\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.context-usage-dialog-body\s*\{[\s\S]*border:\s*0;/);
	assert.match(response.body, /\.context-usage-dialog-body\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /\.chat-run-log-panel\s*\{[\s\S]*border:\s*0;[\s\S]*border-radius:\s*8px;[\s\S]*#060711;/);
	assert.match(response.body, /\.chat-run-log-head\s*\{[\s\S]*border-bottom:\s*0;[\s\S]*background:\s*#101421;/);
	assert.match(response.body, /\.chat-run-log-item\s*\{[\s\S]*border:\s*0;[\s\S]*border-radius:\s*4px;[\s\S]*background:\s*#0b0e19;/);
	assert.match(response.body, /\.confirm-dialog-panel\s*\{[\s\S]*border:\s*0;[\s\S]*border-radius:\s*8px;[\s\S]*background:\s*#0f1624;/);
	assert.match(response.body, /\.confirm-dialog-body\s*\{[\s\S]*border-radius:\s*6px;[\s\S]*background:\s*#151d2e;/);
	assert.match(response.body, /\.confirm-dialog-actions button\s*\{[\s\S]*border:\s*0;[\s\S]*background:\s*#1b2638;/);
	assert.match(response.body, /\.confirm-dialog-actions \.danger-action\s*\{[\s\S]*background:\s*#8d2437;/);
	assert.match(response.body, /\.telemetry-action\[data-tooltip-title\]::after\s*\{[\s\S]*border:\s*0;[\s\S]*border-radius:\s*6px;[\s\S]*background:\s*#111827;/);
	assert.match(response.body, /\.conn-run-details-panel\s*\{[\s\S]*border:\s*0;[\s\S]*background:[\s\S]*#060711;/);
	assert.match(response.body, /\.conn-run-section\s*\{[\s\S]*border:\s*0;[\s\S]*background:\s*#0b0e19;/);
	assert.match(response.body, /function renderContextUsageDialog\(projectedUsage, statusLabel, modeLabel\)/);
	assert.match(response.body, /context-usage-dialog-hero/);
	assert.match(response.body, /context-usage-dialog-metrics/);
	assert.match(response.body, /context-usage-dialog-model/);
	assert.match(response.body, /task-inbox-result-bubble/);
	assert.doesNotMatch(response.body, /后台任务跑完的结果统一收在这里/);
	assert.match(response.body, /task-inbox-head-actions[\s\S]*mark-all-task-inbox-read-button[\s\S]*refresh-task-inbox-button/);
	assert.match(response.body, /\.task-inbox-head\s*\{[\s\S]*align-items:\s*center;[\s\S]*padding:\s*8px 12px;/);
	assert.match(response.body, /\.task-inbox-head\s*\{[\s\S]*background:\s*transparent;/);
	assert.match(response.body, /\.task-inbox-head-actions\s*\{[\s\S]*flex-wrap:\s*nowrap;[\s\S]*overflow-x:\s*auto;/);
	assert.doesNotMatch(response.body, /task-inbox-filter-row/);
	assert.match(response.body, /\.task-inbox-item-title-row\s*\{[\s\S]*grid-template-columns:\s*auto minmax\(0, 1fr\) auto;/);
	assert.match(response.body, /\.task-inbox-item-time\s*\{[\s\S]*font-size:\s*12px;[\s\S]*font-weight:\s*700;/);
	assert.match(response.body, /\.task-inbox-item:not\(\.is-expanded\) \.task-inbox-result-bubble,[\s\S]*\.task-inbox-item:not\(\.is-expanded\) \.task-inbox-item-actions,[\s\S]*\.task-inbox-item:not\(\.is-expanded\) \.task-inbox-item-kind\s*\{[\s\S]*display:\s*none;/);
	assert.match(response.body, /\.task-inbox-item-text\s*\{[\s\S]*font-size:\s*12px;[\s\S]*line-height:\s*1\.7;/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content h1\s*\{[\s\S]*font-size:\s*18px;/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content h2\s*\{[\s\S]*font-size:\s*16px;/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content h3\s*\{[\s\S]*font-size:\s*14px;/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content a\s*\{[\s\S]*color:\s*#8fd6ff;/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content code\s*\{[\s\S]*color:\s*#ffe6ad;/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content blockquote\s*\{[\s\S]*border-left-color:\s*rgba\(128, 232, 198, 0\.46\);/);
	assert.match(response.body, /\.task-inbox-result-bubble \.message-content th\s*\{[\s\S]*background:\s*rgba\(143, 214, 255, 0\.1\);/);
	assert.match(response.body, /text\.className = "task-inbox-item-text message-content"/);
	assert.match(response.body, /text\.innerHTML = renderMessageMarkdown\(resultText\)/);
	assert.match(response.body, /appendFileDownloadList\(body, activity\.files\)/);
	assert.match(response.body, /actions\.className = "task-inbox-item-actions message-actions"/);
	assert.match(response.body, /function openTaskInbox\(/);
	assert.match(response.body, /function loadTaskInbox\(/);
	assert.match(response.body, /function renderTaskInbox\(/);
	assert.doesNotMatch(response.body, /params\.set\("unreadOnly", "true"\)/);
	assert.match(response.body, /function toggleTaskInboxItemExpanded\(activityId\)/);
	assert.match(response.body, /state\.taskInboxExpandedActivityIds = \[\]/);
	assert.match(response.body, /params\.set\("before", state\.taskInboxNextBefore\)/);
	assert.match(response.body, /function applyTaskInboxUnreadCount\(payload\)\s*\{/);
	assert.match(response.body, /function applyConnManagerUnreadCount\(payload\)\s*\{/);
	assert.match(response.body, /state\.taskInboxUnreadCount = page\.unreadCount/);
	assert.match(response.body, /state\.taskInboxUnreadCount = Math\.max\(0, Number\(payload\?\.unreadCount\) \|\| 0\)/);
	assert.match(response.body, /state\.connManagerUnreadCount = Math\.max\(0, Number\(payload\?\.totalUnreadRuns\) \|\| 0\)/);
	assert.match(response.body, /\/v1\/activity\/summary/);
	assert.match(response.body, /\/v1\/conns/);
	assert.match(response.body, /\/v1\/activity\/read-all/);
	assert.match(response.body, /const markAllTaskInboxReadButton = document\.getElementById\("mark-all-task-inbox-read-button"\)/);
	assert.match(response.body, /const mobileOverflowTaskInboxBadge = document\.getElementById\("mobile-overflow-task-inbox-badge"\)/);
	assert.match(response.body, /mobileOverflowTaskInboxBadge\.hidden = unreadCount < 1/);
	assert.match(response.body, /connManagerUnreadBadge\.hidden = connUnreadCount < 1/);
	assert.match(response.body, /mobileOverflowTaskInboxBadge\.textContent = unreadCount > 99 \? "99\+" : String\(unreadCount\)/);
	assert.doesNotMatch(response.body, /markVisibleTaskInboxItemsRead/);
	assert.doesNotMatch(
		response.body,
		/const page = await fetchTaskInboxItems\(\{ append \}\);\s*[\s\S]{0,900}?void syncTaskInboxSummary\(\{ silent: true \}\);/,
	);
	assert.doesNotMatch(
		response.body,
		/const activity = await markTaskInboxItemRead\(activityId\);\s*[\s\S]{0,500}?await syncTaskInboxSummary\(\{ silent: true \}\);/,
	);
	assert.doesNotMatch(
		response.body,
		/const payload = await response\.json\(\)\.catch\(\(\) => \(\{\}\)\);\s*[\s\S]{0,900}?await syncTaskInboxSummary\(\{ silent: true \}\);/,
	);
	assert.match(response.body, /\/v1\/conns"\s*,\s*\{\s*method:\s*"GET"/);
	assert.match(response.body, /\/v1\/conns\/"\s*\+\s*encodeURIComponent\(conn\.connId\)\s*\+\s*"\/run"/);
	assert.match(response.body, /\/v1\/conns\/"\s*\+\s*encodeURIComponent\(conn\.connId\)\s*\+\s*\(conn\.status === "paused" \? "\/resume" : "\/pause"\)/);
	assert.match(response.body, /conn-run-details-dialog/);
	assert.match(response.body, /conn-run-details-body/);
	assert.match(response.body, /conn-run-result-bubble/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content\s*\{[\s\S]*font-size:\s*12px;[\s\S]*line-height:\s*1\.75;/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content h1\s*\{[\s\S]*font-size:\s*18px;/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content h2\s*\{[\s\S]*font-size:\s*16px;/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content h3\s*\{[\s\S]*font-size:\s*14px;/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content a\s*\{[\s\S]*color:\s*#8fd6ff;/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content code\s*\{[\s\S]*color:\s*#ffe6ad;/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content blockquote\s*\{[\s\S]*border-left-color:\s*rgba\(128, 232, 198, 0\.46\);/);
	assert.match(response.body, /\.conn-run-result-bubble \.message-content th\s*\{[\s\S]*background:\s*rgba\(143, 214, 255, 0\.1\);/);
	assert.match(response.body, /resultText\.className = "conn-run-result-text message-content"/);
	assert.match(response.body, /const runResultText = run\.errorText \|\| run\.resultText \|\| run\.resultSummary \|\| "No result summary yet"/);
	assert.match(response.body, /resultText\.innerHTML = renderMessageMarkdown\(runResultText\)/);
	assert.match(response.body, /hydrateMarkdownContent\(resultText\)/);
	assert.doesNotMatch(response.body, /agent-activity-dialog/);
	assert.doesNotMatch(response.body, /agent-activity-list/);
	assert.match(response.body, /source:\s*typeof rawEntry\.source === "string" \? rawEntry\.source : undefined/);
	assert.match(response.body, /sourceId:\s*typeof rawEntry\.sourceId === "string" \? rawEntry\.sourceId : undefined/);
	assert.match(response.body, /runId:\s*typeof rawEntry\.runId === "string" \? rawEntry\.runId : undefined/);
	assert.match(response.body, /source:\s*typeof options\?\.source === "string" \? options\.source : undefined/);
	assert.match(response.body, /sourceId:\s*typeof options\?\.sourceId === "string" \? options\.sourceId : undefined/);
	assert.match(response.body, /runId:\s*typeof options\?\.runId === "string" \? options\.runId : undefined/);
	assert.match(response.body, /\/v1\/conns\/"\s*\+\s*encodeURIComponent\(entry\.sourceId\)\s*\+\s*"\/runs\/"\s*\+\s*encodeURIComponent\(entry\.runId\)/);
	assert.match(response.body, /encodeURIComponent\(entry\.runId\)[\s\S]*"\/events\?"[\s\S]*params\.toString\(\)/);
	assert.match(response.body, /const CONN_RUN_LOG_PAGE_SIZE = 2;/);
	assert.match(response.body, /params = new URLSearchParams\(\{ limit: String\(CONN_RUN_LOG_PAGE_SIZE\) \}\)/);
	assert.match(response.body, /function trimConnRunLogText\(text\)/);
	assert.match(response.body, /connRunDetailsBody\.addEventListener\("scroll"/);
	assert.match(response.body, /loadMoreConnRunEvents\(\)/);
	assert.match(response.body, /:root\[data-theme="light"\] \.conn-run-details-body\s*\{[\s\S]*color:\s*#34435f;/);
	assert.match(response.body, /conn-run-open-button/);
	assert.doesNotMatch(response.body, /appendTranscriptMessage\("error"/);
	assert.doesNotMatch(response.body, /\.message\.error/);
	assert.match(response.body, /\.process-note\s*\{[\s\S]*width: 100%;/);
	assert.match(response.body, /\.process-note-text\s*\{[\s\S]*padding: 0 18px;/);
	assert.match(response.body, /\.process-note-text\s*\{[\s\S]*text-align: left;/);
	assert.match(response.body, /assistant-status-shell/);
	assert.match(response.body, /assistant-status-summary/);
	assert.match(response.body, /assistant-run-log-trigger/);
	assert.match(response.body, /assistant-run-log-hint/);
	assert.match(response.body, /chat-run-log-dialog/);
	assert.match(response.body, /chat-run-log-body/);
	assert.match(response.body, /conversation-item-menu-trigger/);
	assert.match(response.body, /conversation-item-menu/);
	assert.match(response.body, /requestRenameConversation/);
	assert.match(response.body, /requestUpdateConversation/);
	assert.match(response.body, /confirm-dialog/);
	assert.match(response.body, /confirm-dialog-title/);
	assert.match(response.body, /confirm-dialog-confirm/);
	assert.match(response.body, /function openConfirmDialog\(options\)/);
	assert.match(response.body, /function closeConfirmDialog\(confirmed\)/);
	assert.match(response.body, /\.assistant-status-shell\s*\{[\s\S]*display:\s*grid;/);
	assert.match(response.body, /\.assistant-status-shell\s*\{[\s\S]*gap:\s*10px;/);
	assert.match(response.body, /card\.insertBefore\(stream\.shell, body\);/);
	assert.match(response.body, /const assistantLabel = meta\?\.querySelector\("strong"\);/);
	assert.match(response.body, /assistantLabel\.insertAdjacentElement\("afterend", stream\.trigger\);/);
	assert.match(response.body, /state\.activeStatusSummary = stream\.summary;/);
	assert.match(response.body, /state\.activeRunLogTrigger = stream\.trigger;/);
	assert.match(response.body, /\.assistant-status-summary\s*\{[\s\S]*max-width:\s*min\(100%, 560px\);/);
	assert.match(response.body, /\.assistant-status-summary\s*\{[\s\S]*font-size:\s*12px;/);
	assert.match(response.body, /\.assistant-status-summary\s*\{[\s\S]*overflow:\s*hidden;/);
	assert.match(response.body, /\.assistant-status-summary\s*\{[\s\S]*text-overflow:\s*ellipsis;/);
	assert.match(response.body, /\.assistant-status-summary\s*\{[\s\S]*white-space:\s*nowrap;/);
	assert.match(response.body, /@media \(max-width: 640px\) \{[\s\S]*\.message\.assistant \.assistant-status-shell\s*\{[\s\S]*padding:\s*0 2px;/);
	assert.match(response.body, /@media \(max-width: 640px\) \{[\s\S]*\.message\.assistant \.assistant-status-summary\s*\{[\s\S]*color:\s*rgba\(238, 244, 255, 0\.52\);/);
	assert.match(response.body, /@media \(max-width: 640px\) \{[\s\S]*\.message\.assistant \.message-meta \.assistant-loading-bubble\s*\{[\s\S]*height:\s*24px;/);
	assert.match(response.body, /@media \(max-width: 640px\) \{[\s\S]*\.message\.assistant \.message-meta \.assistant-run-log-hint\s*\{[\s\S]*display:\s*none;/);
	assert.match(response.body, /\.message\.assistant \.message-body:has\(> \.message-content\.is-empty:only-child\)\s*\{[\s\S]*display:\s*none;/);
	assert.match(response.body, /\.assistant-loading-bubble\s*\{[\s\S]*display:\s*inline-flex;/);
	assert.match(response.body, /\.assistant-loading-bubble\s*\{[\s\S]*max-width:\s*fit-content;/);
	assert.doesNotMatch(response.body, /assistant-loading-label/);
	assert.match(response.body, /\.assistant-run-log-trigger\s*\{\s*cursor:\s*pointer;/);
	assert.match(response.body, /\.assistant-run-log-trigger:disabled\s*\{[\s\S]*opacity:\s*0\.64;/);
	assert.match(response.body, /\.chat-run-log-dialog\s*\{[\s\S]*place-items:\s*center;/);
	assert.match(response.body, /\.chat-run-log-body\s*\{[\s\S]*overflow:\s*auto;/);
	assert.match(response.body, /const RUN_LOG_PAGE_SIZE = 2;/);
	assert.match(response.body, /params = new URLSearchParams\(\{\s*conversationId,[\s\S]*limit: String\(RUN_LOG_PAGE_SIZE\),/);
	assert.match(response.body, /function trimRunLogText\(text\)/);
	assert.match(response.body, /chatRunLogBody\?\.addEventListener\("scroll"/);
	assert.match(response.body, /loadMoreChatRunLog\(\)/);
	assert.match(response.body, /:root\[data-theme="light"\] \.chat-run-log-item-detail\s*\{[\s\S]*color:\s*#34435f;/);
	assert.match(response.body, /function updateStreamingProcess\(kind, title, detail\)\s*\{\s*appendProcessNarrationLine\(describeProcessNarration\(kind, title, detail\)\);\s*setProcessCurrentAction\(formatProcessAction\(title, detail\), kind\);\s*\}/);
	assert.match(response.body, /function ensureStreamingAssistantMessage\(\)\s*\{[\s\S]*appendTranscriptMessage\("assistant", /);
	assert.doesNotMatch(response.body, /withProcess:\s*true/);
	assert.match(response.body, /function attachAssistantProcessShell\(body, content\)/);
	assert.match(response.body, /function buildAssistantStatusShell\(\)/);
	assert.match(response.body, /function formatProcessSummaryForStatus\(process\)/);
	assert.match(response.body, /function openChatRunLog\(runId, restoreFocusElement\)/);
	assert.match(response.body, /getAgentApiPath\("\/chat\/runs\//);
	assert.doesNotMatch(response.body, /stream\.summary\.textContent = process\.narration\.at\(-1\)/);
	assert.match(response.body, /function setTranscriptState\(next\)\s*\{/);
	assert.match(response.body, /function syncConversationWidth\(\)\s*\{/);
	assert.match(response.body, /const commandDeckWidth = Math\.round\(commandDeckRect\.width \|\| 0\);/);
	assert.match(response.body, /shell\.style\.setProperty\("--conversation-width", commandDeckWidth \+ "px"\);/);
	assert.match(response.body, /function formatProcessAction\(title, detail\)\s*\{[\s\S]*summarizeDetail\(detail\)\.summary/);
	assert.match(response.body, /async function sendMessage\(\)\s*\{[\s\S]*setTranscriptState\("active"\);[\s\S]*resetStreamingState\(\);/);
	assert.match(response.body, /const composerDraft = createComposerDraft\(\);/);
	assert.match(response.body, /updateStreamingProcess\("system", [\s\S]*formatOutboundSummary\(message, attachments, assetRefs\)\);[\s\S]*clearComposerDraft\(\);/);
	assert.match(response.body, /if \(!response\.ok\) \{[\s\S]*restoreComposerDraft\(composerDraft\);/);
	assert.match(response.body, /async function queueActiveMessage\(message, attachments, assetRefs, options\) \{[\s\S]*const composerDraft = options\?\.composerDraft \|\| createComposerDraft\(\);[\s\S]*clearComposerDraft\(\);/);
	assert.match(response.body, /window\.addEventListener\("resize", syncConversationWidth\)/);
	assert.match(response.body, /scheduleConversationLayoutSync\(\{ immediate: true \}\);/);
	assert.match(response.body, /\.composer\s*\{[\s\S]*flex-shrink: 0;/);
	assert.match(response.body, /text\.className = "process-note-text"/);
	assert.doesNotMatch(response.body, /process-feed/);
	assert.doesNotMatch(response.body, /card\.className = "message system process-stream is-running"/);
	assert.doesNotMatch(response.body, /\.message\.process-stream\s*\{/);
	assert.match(response.body, /overflow-y: auto/);
	assert.match(response.body, /message-content/);
	assert.match(response.body, /renderMessageMarkdown/);
	assert.match(response.body, /hydrateMarkdownContent/);
	assert.match(response.body, /copy-code-button/);
	assert.doesNotMatch(response.body, /\.message\.system \.message-meta strong\s*\{/);
	assert.doesNotMatch(response.body, /\.message\.assistant,\s*\.message\.system,\s*\.message\.error\s*\{/);
	assert.match(response.body, /function appendAssistantProcessMessage\(title, text\)\s*\{/);
	assert.match(response.body, /function formatSkillsReply\(skills\)\s*\{/);
	assert.match(response.body, /\.\.\.skillList\.map\(\(skill, index\) => \{/);
	assert.match(response.body, /appendNarrationToAssistantProcess\(skillReply, /);
	assert.match(response.body, /setAssistantProcessAction\(skillReply, [\s\S]*GET " \+ getAgentApiPath\("\/debug\/skills"\), "tool"\)/);
	assert.match(response.body, /setMessageContent\(skillReply\.content, formatSkillsReply\(payload\?\.skills\)\)/);
	assert.match(response.body, /completeAssistantProcessShell\(skillReply, "ok"\)/);
	assert.doesNotMatch(response.body, /appendProcessEvent\("system", [\s\S]*\/v1\/debug\/skills"\)/);
	assert.doesNotMatch(response.body, /appendTranscriptMessage\("system", "闂傚倸鍊搁崐鎼佸磹閹间礁纾归柣鎴ｅГ閸ゅ嫰鏌涢锝嗙缂佺姷濞€閺岀喖宕滆鐢盯鏌涙繝鍌滃煟闁哄本鐩、鏇㈡偐閹绘帒顫撶紓浣哄亾閸庢娊鈥﹂悜钘夎摕闁绘梻鍘х粈鍫㈡喐韫囨洘鏆滄繛鎴欏灪閻?, report\)/);
	assert.match(response.body, /code-block-toolbar/);
	assert.doesNotMatch(response.body, /drag-debug-log/);
	assert.doesNotMatch(response.body, /clear-drag-debug/);
	assert.doesNotMatch(response.body, /asset-library-head/);
	assert.doesNotMatch(response.body, /__name/);
	await app.close();
});
