import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildServer } from "../src/server.js";
import type { AgentService } from "../src/agent/agent-service.js";

function createAgentServiceStub() {
	return {
		chat: async () => ({ reply: "ok", conversationId: "c1", runId: "r1" }),
		streamChat: async () => {},
		queueMessage: async () => ({ reply: "ok", conversationId: "c1", runId: "r1" }),
		interruptChat: async () => {},
		resetConversation: async () => {},
		getAgentRunStatus: async () => ({ conversationId: "c1", running: false }),
		getRunStatus: async () => ({ conversationId: "c1", running: false, contextUsage: { provider: "p", model: "m", currentTokens: 0, contextWindow: 128000, reserveTokens: 16000, maxResponseTokens: 8000, availableTokens: 112000, percent: 0, status: "safe" as const, mode: "usage" as const } }),
		subscribeRunEvents: () => ({ conversationId: "c1", running: false, unsubscribe: () => {} }),
		getRunEvents: async () => [],
		getConversations: async () => [],
		getConversation: async () => null,
		createConversation: async () => ({ id: "c1", title: "t", createdAt: "", updatedAt: "" }),
		switchConversation: async () => {},
		deleteConversation: async () => {},
	} as unknown as AgentService;
}

async function buildTestServer() {
	const root = await mkdtemp(join(tmpdir(), "team-api-"));
	const teamDir = join(root, "team");
	process.env.TEAM_RUNTIME_ENABLED = "true";
	process.env.TEAM_DATA_DIR = teamDir;
	const app = await buildServer({ agentService: createAgentServiceStub() });
	return { app, root, teamDir };
}

const unitBody = {
	title: "调研团队",
	description: "测试用",
	watcherProfileId: "main",
	workerProfileId: "main",
	checkerProfileId: "main",
	finalizerProfileId: "main",
};

const planBody = (teamUnitId: string) => ({
	title: "测试计划",
	defaultTeamUnitId: teamUnitId,
	goal: { text: "测试目标" },
	tasks: [{ id: "t1", title: "任务1", input: { text: "做任务1" }, acceptance: { rules: ["规则1"] } }],
	outputContract: { text: "输出" },
});

// ── P16 Task 2: Dynamic plan API acceptance ──

const dynamicPlanBody = (teamUnitId: string) => ({
	title: "Dynamic discovery plan",
	defaultTeamUnitId: teamUnitId,
	goal: { text: "Discover and process items" },
	tasks: [
		{ id: "discover", type: "discovery", title: "Discover items", input: { text: "Search for items related to X" }, acceptance: { rules: ["output is valid JSON with 'items' array"] }, discovery: { outputKey: "items" } },
		{ id: "process_each", type: "for_each", title: "Process each", input: { text: "Placeholder" }, acceptance: { rules: ["output valid for {{item.id}}"] }, forEach: { itemsFrom: "discover.items", mode: "sequential", taskTemplate: { title: "Process {{item.title}}", input: { text: "Analyze item {{item.id}}" }, acceptance: { rules: ["output contains analysis for {{item.id}}"] } } } },
	],
	outputContract: { text: "Summary report" },
});

test("P16-T2: API accepts dynamic plan generated by UI builder", async () => {
	const { app, root } = await buildTestServer();
	try {
		const unitRes = await app.inject({ method: "POST", url: "/v1/team/team-units", payload: unitBody });
		const unitId = unitRes.json().teamUnitId;
		const res = await app.inject({ method: "POST", url: "/v1/team/plans", payload: dynamicPlanBody(unitId) });
		assert.equal(res.statusCode, 201);
		const plan = res.json();
		assert.equal(plan.tasks.length, 2);
		assert.equal(plan.tasks[0].type, "discovery");
		assert.equal(plan.tasks[0].discovery.outputKey, "items");
		assert.equal(plan.tasks[1].type, "for_each");
		assert.equal(plan.tasks[1].forEach.itemsFrom, "discover.items");
		assert.equal(plan.tasks[1].forEach.taskTemplate.title, "Process {{item.title}}");
		await app.close();
	} finally {
		try { await rm(root, { recursive: true, force: true }); } catch {}
	}
});

test("P16-T2: API rejects dynamic plan with empty child template acceptance rules", async () => {
	const { app, root } = await buildTestServer();
	try {
		const unitRes = await app.inject({ method: "POST", url: "/v1/team/team-units", payload: unitBody });
		const unitId = unitRes.json().teamUnitId;
		const body = dynamicPlanBody(unitId);
		body.tasks[1]!.forEach!.taskTemplate!.acceptance = { rules: [] };
		const res = await app.inject({ method: "POST", url: "/v1/team/plans", payload: body });
		assert.equal(res.statusCode, 400);
		assert.match(res.json().error, /acceptance/i);
		await app.close();
	} finally {
		try { await rm(root, { recursive: true, force: true }); } catch {}
	}
});

test("P16-T2: normal one-task plan still works via API", async () => {
	const { app, root } = await buildTestServer();
	try {
		const unitRes = await app.inject({ method: "POST", url: "/v1/team/team-units", payload: unitBody });
		const planRes = await app.inject({ method: "POST", url: "/v1/team/plans", payload: planBody(unitRes.json().teamUnitId) });
		assert.equal(planRes.statusCode, 201);
		assert.equal(planRes.json().tasks.length, 1);
		assert.equal(planRes.json().tasks[0].type, undefined);
		await app.close();
	} finally {
		try { await rm(root, { recursive: true, force: true }); } catch {}
	}
});

// ── P21-B: task decomposer plan API validation ──

test("POST plan accepts task decomposer policy", async () => {
	const { app, root } = await buildTestServer();
	try {
		const unitRes = await app.inject({ method: "POST", url: "/v1/team/team-units", payload: unitBody });
		const unitId = unitRes.json().teamUnitId;
		const res = await app.inject({ method: "POST", url: "/v1/team/plans", payload: {
			title: "Decomposer plan",
			defaultTeamUnitId: unitId,
			goal: { text: "split where needed" },
			tasks: [
				{ id: "t1", title: "Split task", input: { text: "do" }, acceptance: { rules: ["ok"] }, decomposer: { mode: "propagate", maxChildren: 5 } },
			],
			outputContract: { text: "out" },
		}});
		assert.equal(res.statusCode, 201);
		assert.equal(res.json().tasks[0].decomposer.mode, "propagate");
		await app.close();
	} finally {
		try { await rm(root, { recursive: true, force: true }); } catch {}
	}
});

test("POST plan rejects invalid task decomposer policy", async () => {
	const { app, root } = await buildTestServer();
	try {
		const unitRes = await app.inject({ method: "POST", url: "/v1/team/team-units", payload: unitBody });
		const unitId = unitRes.json().teamUnitId;
		const res = await app.inject({ method: "POST", url: "/v1/team/plans", payload: {
			title: "Bad decomposer plan",
			defaultTeamUnitId: unitId,
			goal: { text: "split where needed" },
			tasks: [
				{ id: "t1", title: "Split task", input: { text: "do" }, acceptance: { rules: ["ok"] }, decomposer: { mode: "recursive_forever", maxChildren: 5 } },
			],
			outputContract: { text: "out" },
		}});
		assert.equal(res.statusCode, 400);
		assert.match(res.json().error, /decomposer\.mode/);
		await app.close();
	} finally {
		try { await rm(root, { recursive: true, force: true }); } catch {}
	}
});

test("PATCH plan rejects invalid forEach taskTemplate decomposer policy when runCount=0", async () => {
	const { app, root } = await buildTestServer();
	try {
		const unitRes = await app.inject({ method: "POST", url: "/v1/team/team-units", payload: unitBody });
		const unitId = unitRes.json().teamUnitId;
		const createRes = await app.inject({ method: "POST", url: "/v1/team/plans", payload: planBody(unitId) });
		const planId = createRes.json().planId;
		const res = await app.inject({ method: "PATCH", url: `/v1/team/plans/${planId}`, payload: {
			tasks: [{
				id: "process_each", type: "for_each", title: "Process each",
				input: { text: "placeholder" },
				acceptance: { rules: ["ok"] },
				forEach: {
					itemsFrom: "discover.items",
					mode: "sequential",
					taskTemplate: {
						title: "Process {{item.title}}",
						input: { text: "Process" },
						acceptance: { rules: ["ok"] },
						decomposer: { mode: "bad" },
					},
				},
			}],
		}});
		assert.equal(res.statusCode, 400);
		assert.match(res.json().error, /taskTemplate\.decomposer\.mode/);
		await app.close();
	} finally {
		try { await rm(root, { recursive: true, force: true }); } catch {}
	}
});
